### ISSUE TITLE
Multiple Contexts

### ISSUE THREAD

**Issue by mchristianl** [Gnimuc/CImGui.jl#1]
Hello, I have just recently read about this Wrapper. Thank you for porting!

For a multi-window setup I found that `SetCurrentContext` is exported, but additionally I had to manually save and restore all global variables `g_*` from `CImGui.OpenGLBackend` and `CImGui.GLFWBackend`

per-window setup

```julia
  if isa(state.lastImGuiPlot,Base.RefValue)
    saveImGuiState(state.lastImGuiPlot[])
    state.lastImGuiPlot = Ptr{PlotState}(C_NULL)
  end
  CImGui.OpenGLBackend.__init__()
  CImGui.GLFWBackend.__init__()
  p.imguictx = CImGui.CreateContext()
  CImGui.SetCurrentContext(p.imguictx)
  CImGui.StyleColorsDark()
  ImGui_ImplGlfw_InitForOpenGL(p.window, false)
  ImGui_ImplOpenGL3_Init(glversion)
  saveImGuiState(p)
```

rendering:

```julia
    CImGui.SetCurrentContext(p.imguictx)
    restoreImGuiState(p)
    ImGui_ImplOpenGL3_NewFrame()
    ImGui_ImplGlfw_NewFrame()
    CImGui.NewFrame()
    ...
```

with something like this

```julia
function saveImGuiState(p :: PlotState)
  p.imgui_opengl_state.g_AttribLocationColor     = CImGui.OpenGLBackend.g_AttribLocationColor
  p.imgui_opengl_state.g_AttribLocationTex       = CImGui.OpenGLBackend.g_AttribLocationTex
  p.imgui_opengl_state.g_FontTexture             = CImGui.OpenGLBackend.g_FontTexture
  p.imgui_opengl_state.g_ImageTexture            = CImGui.OpenGLBackend.g_ImageTexture
  p.imgui_opengl_state.g_VertHandle              = CImGui.OpenGLBackend.g_VertHandle
  p.imgui_opengl_state.g_AttribLocationPosition  = CImGui.OpenGLBackend.g_AttribLocationPosition
  p.imgui_opengl_state.g_AttribLocationUV        = CImGui.OpenGLBackend.g_AttribLocationUV
  p.imgui_opengl_state.g_FragHandle              = CImGui.OpenGLBackend.g_FragHandle
  p.imgui_opengl_state.g_ShaderHandle            = CImGui.OpenGLBackend.g_ShaderHandle
  p.imgui_opengl_state.g_AttribLocationProjMtx   = CImGui.OpenGLBackend.g_AttribLocationProjMtx
  p.imgui_opengl_state.g_ElementsHandle          = CImGui.OpenGLBackend.g_ElementsHandle
  p.imgui_opengl_state.g_GlslVersion             = CImGui.OpenGLBackend.g_GlslVersion
  p.imgui_opengl_state.g_VboHandle               = CImGui.OpenGLBackend.g_VboHandle

  p.imgui_glfw_state.g_ClientApi                 = CImGui.GLFWBackend.g_ClientApi
  p.imgui_glfw_state.g_ImplGlfw_SetClipboardText = CImGui.GLFWBackend.g_ImplGlfw_SetClipboardText
  p.imgui_glfw_state.g_MouseJustPressed          = CImGui.GLFWBackend.g_MouseJustPressed
  p.imgui_glfw_state.g_Window                    = CImGui.GLFWBackend.g_Window
  p.imgui_glfw_state.g_ImplGlfw_GetClipboardText = CImGui.GLFWBackend.g_ImplGlfw_GetClipboardText
  p.imgui_glfw_state.g_MouseCursors              = CImGui.GLFWBackend.g_MouseCursors
  p.imgui_glfw_state.g_Time                      = CImGui.GLFWBackend.g_Time
end

function restoreImGuiState(p :: PlotState)
  if isa(state.lastImGuiPlot,Base.RefValue)
    saveImGuiState(state.lastImGuiPlot[])
  end
  state.lastImGuiPlot = Ref(p)
  CImGui.OpenGLBackend.Set_g_AttribLocationColor(    p.imgui_opengl_state.g_AttribLocationColor)
  CImGui.OpenGLBackend.Set_g_AttribLocationTex(      p.imgui_opengl_state.g_AttribLocationTex)
  CImGui.OpenGLBackend.Set_g_FontTexture(            p.imgui_opengl_state.g_FontTexture)
  CImGui.OpenGLBackend.Set_g_ImageTexture(           p.imgui_opengl_state.g_ImageTexture)
  CImGui.OpenGLBackend.Set_g_VertHandle(             p.imgui_opengl_state.g_VertHandle)
  CImGui.OpenGLBackend.Set_g_AttribLocationPosition( p.imgui_opengl_state.g_AttribLocationPosition)
  CImGui.OpenGLBackend.Set_g_AttribLocationUV(       p.imgui_opengl_state.g_AttribLocationUV)
  CImGui.OpenGLBackend.Set_g_FragHandle(             p.imgui_opengl_state.g_FragHandle)
  CImGui.OpenGLBackend.Set_g_ShaderHandle(           p.imgui_opengl_state.g_ShaderHandle)
  CImGui.OpenGLBackend.Set_g_AttribLocationProjMtx(  p.imgui_opengl_state.g_AttribLocationProjMtx)
  CImGui.OpenGLBackend.Set_g_ElementsHandle(         p.imgui_opengl_state.g_ElementsHandle)
  CImGui.OpenGLBackend.Set_g_GlslVersion(            p.imgui_opengl_state.g_GlslVersion)
  CImGui.OpenGLBackend.Set_g_VboHandle(              p.imgui_opengl_state.g_VboHandle)

  CImGui.GLFWBackend.Set_g_ClientApi(                 p.imgui_glfw_state.g_ClientApi)
  CImGui.GLFWBackend.Set_g_ImplGlfw_SetClipboardText( p.imgui_glfw_state.g_ImplGlfw_SetClipboardText)
  CImGui.GLFWBackend.Set_g_MouseJustPressed(          p.imgui_glfw_state.g_MouseJustPressed)
  CImGui.GLFWBackend.Set_g_Window(                    p.imgui_glfw_state.g_Window)
  CImGui.GLFWBackend.Set_g_ImplGlfw_GetClipboardText( p.imgui_glfw_state.g_ImplGlfw_GetClipboardText)
  CImGui.GLFWBackend.Set_g_MouseCursors(              p.imgui_glfw_state.g_MouseCursors)
  CImGui.GLFWBackend.Set_g_Time(                      p.imgui_glfw_state.g_Time)
end
```

Is there a chance to have these two variable-sets attached to the "current" ImGui context?

regards,
Christian

**Comment by Gnimuc** [comment]
These global GLFW/OpenGL states are holding temporarily only for rendering purpose. They're not ImGui states. Almost all of them are refreshed in every rendering loop when calling: 
```
ImGui_ImplOpenGL3_NewFrame()
ImGui_ImplGlfw_NewFrame()
```
except `g_Window` and `g_FontTexture`.  The hot-fix would be to remove the optimization trick `g_FontTexture == 0` used in this line:

https://github.com/Gnimuc/CImGui.jl/blob/2b6caaaf4b082dadf08786aef3e802aa7abd9293/src/backend/OpenGL/impl.jl#L30

and make `ImGui_ImplGlfw_NewFrame()` aware of current GLFW window context:
https://github.com/Gnimuc/CImGui.jl/blob/2b6caaaf4b082dadf08786aef3e802aa7abd9293/src/backend/GLFW/impl.jl#L129

```
function ImGui_ImplGlfw_NewFrame(window)
    global g_Time
    global g_Window = window
```
then this modified example will work:
https://gist.github.com/Gnimuc/b9308bb8ed0a81b4fe1e76d706837f3d

**Comment by mchristianl** [comment]
Thank you for the example!

> except g_Window and g_FontTexture

nice.

I am still experiencing some issues with that fix, that seem to be related to the event handling: for example, in your code multicontext.jl I _sometimes_ cannot close window1 and only window2 and _sometimes_ the other way around.

Also it seems that currently there is no possiblity to [manage the callbacks manually](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_glfw.h) via

`ImGui_ImplGlfw_MouseButtonCallback`
`ImGui_ImplGlfw_ScrollCallback`
`ImGui_ImplGlfw_KeyCallback`
`ImGui_ImplGlfw_KeyCallback`

which might be of interest also for single multiple contexts.

regards,

**Comment by Gnimuc** [comment]
That's because the script didn't destory GLFW windows instance in the rendering loop: https://gist.github.com/Gnimuc/b9308bb8ed0a81b4fe1e76d706837f3d#file-multicontext-jl-L118-L123
This can be fixed by something like:
```
# in rendering loop
GLFW.PollEvents()
if GLFW.WindowShouldClose(window1)
    CImGui.DestroyContext(ctx1)
    GLFW.DestroyWindow(window1)
end
```

As for the callbacks, I didn't implement that because I thought they were not very useful in that one can always overload these callbacks before GLFW initialization. But this feature is very simple to implement by following:     
https://github.com/ocornut/imgui/blob/d9568c717de8ec53445bad00be73133f1a110317/examples/imgui_impl_glfw.cpp#L82-L83 

so feel free to submit a PR. Or I'll fix it this weekend.

**Comment by mchristianl** [comment]
Indeed, I got it working in the way you proposed; the "issues" were just in my implementation. Could resolve them now

**Comment by Gnimuc** [comment]
UPDATE:

Now the master branch supports multi-viewport and this multiple contexts support is being removed since it's not recommended to use Dear ImGui in this way. Also, see #52.
