### ISSUE TITLE
Document how to recompile cimgui with patches or additional extensions

### ISSUE THREAD

**Issue by jpsamaroo** [Gnimuc/CImGui.jl#10]
Since Dear ImGui is often patched or extended to support new features or improve in certain areas of the library, it's often a desire of mine to be able to recompile the underlying C++ library with a patched Dear ImGui codebase. I haven't yet tried to do this, because it isn't documented :smile: Is there any chance we could have a simple set of step-by-step instructions on how to do this?

**Comment by Gnimuc** [comment]
I'm going to add some docs and upgrade IMGUI to 1.72 this weekend.

**Comment by Gnimuc** [comment]
Please refer to https://github.com/Gnimuc/CImGuiBuilder#how-to-build-locally

**Comment by jpsamaroo** [comment]
Thanks!
