### ISSUE TITLE
Broken after update

### ISSUE THREAD

**Issue by heyx3** [Gnimuc/CImGui.jl#100]
Hi, it looks like LibCImGui.jl has some updated code that CImGui is not able to deal with? I got the "KeyPadEnter" error already mentioned by somebody else, and after fixing it in my own code I'm getting "`igTreeNodeStr(label)` not defined" when calling `TreeNode()`. Because it's been updated to `igTreeNode_Str(label)`.

The package versions I'm using are:

* CImGui: 1.82.0
* LibCImGui: 1.89.5
* CImGuiPack_jll: 0.2.0+0

**Comment by wsphillips** [comment]
You need the updates to the GLFW and OpenGL backends to use LibCImGui 1.89. On the tagged release of CImGui 1.82 the compat hasnt been updated. For the moment, try `] add CImGui#master` and and running `] up` after. You should see the backends update to v0.2.0 and then it should work.

@Gnimuc I think we need to do some compat hygeine and perhaps tag a separate v1.89 release? v1.89 should have minimum bound of v0.2.0 for GLFW and OpenGL backend and v1.82 should be <0.2.0 for both

**Comment by heyx3** [comment]
I'm not using the built-in backends, I have my own.

**Comment by heyx3** [comment]
In the short-term, what versions of these three packages can I go back to to get the older functional version of the package?

**Comment by Gnimuc** [comment]
I think the broken version has been yanked.

**Comment by Gnimuc** [comment]
cc @JamesWrigley

**Comment by heyx3** [comment]
Thanks, I fixed it by reverting to CImGui v1.82.0 and LibCimGui v1.82.2

**Comment by JamesWrigley** [comment]
Umm, so I think the issue is that CImGui 1.82 and LibCImGui 1.89.5 are incompatible. I'd say we should have a new patch release of CImGui 1.82 with this PR: https://github.com/Gnimuc/CImGui.jl/pull/90
And then maybe a breaking CImGui 1.89 release with all the 1.89 changes from https://github.com/Gnimuc/CImGui.jl/pull/87.

**Comment by JamesWrigley** [comment]
Things should be working again with v1.82.1 :crossed_fingers:
