### ISSUE TITLE
Incomplete overlap

### ISSUE THREAD

**Issue by FaresX** [Gnimuc/CImGui.jl#109]
When I use CImGui.SetItemAllowOverlap of version 1.89 for two widgets, the latter one can be hovered but not activated. It's fine for 1.82.

**Comment by JamesWrigley** [comment]
It hasn't been wrapped yet, but could you try using `CImGui.igSetNextItemAllowOverlap()`? Apparently `SetItemAllowOverlap()` was deprecated in 1.89.7, which is after our version of 1.89.5, but I'm wondering if it was broken earlier: https://github.com/ocornut/imgui/blob/docking/imgui.h#L3448

**Comment by FaresX** [comment]
Thank you for your reply. The problem is still there. I have implemented by other methods instead, looking forward to updating to the latest version.

**Comment by JamesWrigley** [comment]
Ok, we'll keep this open until the next update. Out of curiosity, how did you get around the bug?

**Comment by FaresX** [comment]
I used buttons as background to display text and placed other widgets on the top of them. Now I have switched to drawing rectangles. What I'm doing may be limited to my needs.
