### ISSUE TITLE
UndefVarError: `igSetScrollYFloat` not defined

### ISSUE THREAD

**Issue by sairus7** [Gnimuc/CImGui.jl#113]
I've encountered ```UndefVarError: `igSetScrollYFloat` not defined``` from this line: https://github.com/Gnimuc/CImGui.jl/blob/master/src/wrapper.jl#L538

Looks like LibCImGui has different function name `igSetScrollY_Float` that is not reflected in wrapper.jl here?
https://github.com/JuliaImGui/LibCImGui.jl/blob/master/lib/x86_64-w64-mingw32.jl#L4457

Looks like the same applies to `igSetScrollXFloat`. Is wrapper.jl file auto-generated or manually written?

**Comment by JamesWrigley** [comment]
Oh dear, that's probably something I missed during the last upgrade :grimacing: `wrapper.jl` is manually written, but at some point we/I should rewrite it to be generated automagically.
