### ISSUE TITLE
`AddRect()` error: "`ImDrawCornerFlags_All` not defined"

### ISSUE THREAD

**Issue by heyx3** [Gnimuc/CImGui.jl#117]
In Julia 1.9.2, CImGui 1.82.0:

````
julia> using CImGui
julia> CImGui.AddRect(Ptr{CImGui.ImDrawList}(C_NULL), CImGui.ImVec2(0.5, 0.5), CImGui.ImVec2(10, 20), 0x1234)

ERROR: UndefVarError: `ImDrawCornerFlags_All` not defined
````

Presumably it should be `ImDrawFlags_RoundCornersAll`

**Comment by JamesWrigley** [comment]
Thanks for the report, could you try my branch in #118 and see if that fixes it? If so I'll merge it and tag a new release.

**Comment by heyx3** [comment]
Yep! No longer errors on my machine

**Comment by heyx3** [comment]
I really wish Julia had some kind of static analyzer to warn of potential unknown variable accesses :\

**Comment by JamesWrigley** [comment]
Alrighty, the new version should be available soon: https://github.com/JuliaRegistries/General/pull/108414

> I really wish Julia had some kind of static analyzer to warn of potential unknown variable accesses :\

Yeah I agree. What we really need is proper tests (#98), but in the meantime maybe JET.jl might be of use to find those kind of errors :thinking: In the past it's been a little spammy but maybe there are some settings to only look for obvious errors like unknown variables.
