### ISSUE TITLE
How to start? 

### ISSUE THREAD

**Issue by gsal** [Gnimuc/CImGui.jl#28]
Bummer, this looks nice, but I have no idea how to start.   

As the README indicates in the very first paragraph...this is a Julia wrapper of cimgui, which in turn is a C wrapper of the C++ Dear ImGui ...So, what am I to do if I am coming from Julia and have never heard of any of these 3? Do I need to learn Dear ImGui, first; then, cimgui; then, CImGui.jl ? 

Also, for installation, it just says to do `add CImGui` ...is that it? 'cause non of the examples run correctly; nothing visual happens, just get the prompt back. . Any dependencies ?

**Comment by Gnimuc** [comment]
> As the README indicates in the very first paragraph...this is a Julia wrapper of cimgui, which in turn is a C wrapper of the C++ Dear ImGui ...So, what am I to do if I am coming from Julia and have never heard of any of these 3? Do I need to learn Dear ImGui, first; then, cimgui; then, CImGui.jl ?

This package is rather low-level and the package itself doesn't provide any additional features that Dear ImGui does not provide, so learning Dear ImGui is basically equivalent to learning cimgui and CImGui.jl. 

Dear ImGui is documented by [these examples](https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp) and there is an [interactive manual](https://pthom.github.io/imgui_manual_online/manual/imgui_manual.html). A majority of those codes are one-to-one ported to Julia [here](https://github.com/Gnimuc/CImGui.jl/tree/master/examples), the demo.jl is where to start. 

One thing that is necessary but the package doesn't provide is the [rendering loop](https://github.com/Gnimuc/CImGui.jl/blob/master/examples/demo.jl#L76-L113). If you'd like to render the whole thing via a function, you could wrap those stuff into a module like [this one](https://github.com/Gnimuc/Redux.jl/blob/master/examples/Renderer.jl) and then use it like this: https://github.com/Gnimuc/Redux.jl/blob/master/examples/counter/app.jl#L32

For simple UIs, it's enough to just use global variables to manage UI states, but as the UI states grow larger, it's inevitable to use some state-management framework like Redux and the "Redux" version of ImGui is working in progress [here](https://github.com/Gnimuc/ReduxImGui.jl).

> Also, for installation, it just says to do `add CImGui` ...is that it? 'cause non of the examples run correctly; nothing visual happens, just get the prompt back. . Any dependencies ?

Could you share some versioninfo or try the following code? 

```
(@v1.4) pkg> activate new_env
 Activating new environment at `~/new_env/Project.toml`

(new_env) pkg> add CImGui
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
  Installed CImGui ─ v1.77.0
   Updating `~/new_env/Project.toml`
  [5d785b6c] + CImGui v1.77.0

julia> using CImGui, Pkg
[ Info: Precompiling CImGui [5d785b6c-b76f-510e-a07c-3070796c7e87]

julia> include(joinpath(pathof(CImGui), "..", "..", "examples", "demo.jl"))
```

**Comment by gsal** [comment]
Thanks for all the pointers.   That command works just fine, by the way; I guess `demo.jl` _is_ the entry point and the other files cannot be run by themselves. 

Thanks, again.
