### ISSUE TITLE
ImGui Docking Support

### ISSUE THREAD

**Issue by cshenton** [Gnimuc/CImGui.jl#34]
What would need to be done to support ImGui docking? 

Upstream, `cimgui` appears to have a docking branch, so I imagine it's just a matter of updating the `Yggdrasil` build script to target the appropriate commits of ImGui and cimgui. However, where I get a bit lost is on how to connect everything together.

Should someone hoping to add this support create PRs in Yggdrasil, CimGui_jll, and this repo? Should those PRs _all_ target a separate branch, or should Yggdrasil's PR target master but in a different subfolder?

**Comment by Gnimuc** [comment]
> Should someone hoping to add this support create PRs in Yggdrasil, CimGui_jll, and this repo?

Only PRs to Yggdrasil and this repo are needed. If you submit a PR to Yggdrasil, XXX_jll will be automatically published or updated.

> Should those PRs _all_ target a separate branch, or should Yggdrasil's PR target master but in a different subfolder?

In a different subfolder.

I considered adding docking support a while ago, the main problem is versioning. If we maintain two branches, what version should be used for the docking branch?

**Comment by wsphillips** [comment]
I think docking and table branches are considered WIP to be eventually added to mainline imgui anyhow?

**Comment by Gnimuc** [comment]
It looks like the table branch will be merged in the near future, but the docking/viewport branch is still relatively unstable and blocked by a few issues.
