### ISSUE TITLE
Is there a way to use the gr framework with CImGui.jl?

### ISSUE THREAD

**Issue by yadmtr** [Gnimuc/CImGui.jl#37]
Is there a way to use the  [gr framework](https://github.com/jheinen/GR.jl) (or [GRUtils](https://github.com/heliosdrm/GRUtils.jl)) with CImGui.jl ?

**Comment by Gnimuc** [comment]
If you're talking about how to use GR as a backend for CImGui.jl, then it is possible as long as GR exposes its OpenGL context and a callback function for hacking into its rendering loop. You might also be interested in the following post:
https://discourse.julialang.org/t/is-it-possible-to-use-makie-in-cimgui/45844/2

**Comment by yadmtr** [comment]
Thanks this post was what I needed.

```Julia
using GRUtils
using Printf

ENV["GKS_WSTYPE"] = "100" # off-screen rendering
y  =  rand(1001)
img_width, img_height = 400, 400
image = rand(GLuint, 4, img_width, img_height) # allocate the memory 
GRUtils.colorscheme("LIGHT")
fg = GRUtils.plot( y) 
str_pointer = Printf.@sprintf("%p",pointer(image))
filename = Printf.@sprintf("!%dx%d@%s.mem",  img_width, img_height,str_pointer[3:end])
GC.@preserve image savefig(filename, fg) #  write an image directly to memory as 32-bit RGBA
...
# creat texture for image drawing
image_id = ImGui_ImplOpenGL3_CreateImageTexture(img_width, img_height)
# show image
CImGui.Begin("Image Demo")
ImGui_ImplOpenGL3_UpdateImageTexture(image_id, image, img_width, img_height)
CImGui.Image(Ptr{Cvoid}(image_id), (img_width, img_height))
CImGui.End()
...
```
![Снимок экрана 2021-01-24 142405](https://user-images.githubusercontent.com/75506237/105628766-eb6abb80-5e4f-11eb-8c6c-199c411aef3e.png)
