### ISSUE TITLE
update to v1.80

### ISSUE THREAD

**Issue by yadmtr** [Gnimuc/CImGui.jl#38]
cimgui now supports v1.80 (with tables), please update CImGui if possible.

And could you return to the [docking support](https://github.com/Gnimuc/CImGui.jl/issues/34#issuecomment-706151960) question, please.

**Comment by Gnimuc** [comment]
Sorry, I'm currently reworking Clang.jl and don't have much time on this.

**Comment by sefffal** [comment]
If I were to submit a PR to update CImGui_jll to the latest version, would that help? Or is the main challenge in updating the Julia bindings?

**Comment by Gnimuc** [comment]
updating the Julia bindings, since Clang.jl cannot handle forward decls correctly, we cannot regenerate those bindings by one click, that's exactly why I'm reworking Clang.jl.

**Comment by sairus7** [comment]
Is there some workaround to show tables in 1.79 before 1.80 is added?
