### ISSUE TITLE
Tag a 1.82.0 release?

### ISSUE THREAD

**Issue by sairus7** [Gnimuc/CImGui.jl#62]
What should be done do make this release?

**Comment by Gnimuc** [comment]
Here is a list that I can come up with at the moment:
 
1. Update README and document the major change about loading/writing pointers(basically what I wrote in #52) 
2. Manually test all widgets in the demo.jl and enable docking by default
3. Disable multi-viewport support by default and add warnings(multi-viewport support does not work correctly on Window)

**Comment by Gnimuc** [comment]
4. Add wrappers for 1.79~1.82 new APIs (the new Table API is the major one)

**Comment by sairus7** [comment]
Looks like there are missing some exports for table-related functions and flags, like `BeginTable`. I see only names like `igBeginTable`. Should I start working with these names, or manually edit `wrapper.jl`, with a bunch of `BeginTable() = igBeginTable()` lines?

Or you can re-generate this file @Gnimuc ?

**Comment by Gnimuc** [comment]
`wrapper.jl` is written by hand, so we need to add those thin wrappers manually, but I don't have time to maintain this project at the moment. Do you need push access? I can send you an invitation as a collaborator.

**Comment by sairus7** [comment]
Yes, would try to add it manually.

Also, are there any other changes that should be made to LibCImGui generated code and exports, or all names are already there?

**Comment by Gnimuc** [comment]
> Also, are there any other changes that should be made to LibCImGui generated code and exports, or all names are already there?

LibCImGui is now fully auto-generated, so all symbols should be exported.

**Comment by IanButterworth** [comment]
Seems like this can be closed?
