### ISSUE TITLE
Columns - Horizontal Scroll demo not working in v1.79.0

### ISSUE THREAD

**Issue by brianquesadilla** [Gnimuc/CImGui.jl#71]
Hi, I'm new to Julia and not a software engineer, so my apologies in advance if I'm off here. I was trying to debug one of the demo examples for CImGui v1.79.0, specifically 
    Columns -> Horizontal Scrolling 
that causes the GUI to crash and I (cautiously) think I found a simple bug that fixes it and that it hasn't been corrected yet in newer versions. Just a an mixup of `self` and `handle` in `Begin` defined in `wrappers.jl`:

    # the relevant code is this:
    # Begin(handle::Ptr{ImGuiListClipper}, items_count, items_height=-1.0) = ImGuiListClipper_Begin(self, items_count, items_height)

    # but should be this:
    Begin(handle::Ptr{ImGuiListClipper}, items_count, items_height=-1.0) = ImGuiListClipper_Begin(handle, items_count, items_height)

I'm not familiar with the version control pull request procedure stuff to suggest a code change, but was hoping someone who is could help fix it. Thanks.

**Comment by Gnimuc** [comment]
Thanks for reporting the issue. Fixed and tagged: https://github.com/JuliaRegistries/General/pull/70368

**Comment by brianquesadilla** [comment]
Thanks for your help!

**Comment by JamesWrigley** [comment]
Closing this since it was fixed.
