### ISSUE TITLE
Example code doesn't actually run

### ISSUE THREAD

**Issue by jpsamaroo** [Gnimuc/CImGui.jl#76]
The code in `examples`/ is apparently unused, with the real demo window being provided by `CImGui.ShowDemoWindow`. Is there a reason for this? I've noticed that the code in the examples doesn't all work; for example, `ImDrawCornerFlags_*` are no longer defined in CImGui, causing the custom rendering examples to break.

**Comment by Gnimuc** [comment]
Which version are you working on? Those examples are not upgraded to v1.82.

**Comment by jpsamaroo** [comment]
I'm on v1.82, so I guess we probably should update the generator to provide those flags?

**Comment by Gnimuc** [comment]
We need to update those examples.

**Comment by Gnimuc** [comment]
Maybe we should remove some outdated examples.

**Comment by heyx3** [comment]
Ah, I was about to make an issue about this but found this thread.

The following line of code in the demos is also a problem: `unsafe_load(io.Fonts.TexID)`; the `Fonts` pointer does not appear to have an overloaded `getproperty()` like many other ImGUI pointers.

For the record, the snippet I was using to run the demo window is: `julia --project=. -e 'include(\"examples/Renderer.jl\"); include(\"examples/demo_window.jl\"); Renderer.render(() -> begin; p = Ref(false); ShowDemoWindow(p); end)'`

**Comment by heyx3** [comment]
If there is a reference somewhere for the breaking changes that were made, I can update these demos?
