### ISSUE TITLE
How can I get ImGuiWindowClass?

### ISSUE THREAD

**Issue by FaresX** [Gnimuc/CImGui.jl#80]
I read the imgui_demo.cpp from https://pthom.github.io/imgui_manual_online/manual/imgui_manual.html to find the usage of dockspace
```
 ImGui::DockSpaceOverViewport(ImGui::GetMainViewport());
```
but in LibCImGui, it is like this
```
function igDockSpaceOverViewport(viewport, flags, window_class)
    ccall((:igDockSpaceOverViewport, libcimgui), ImGuiID, (Ptr{ImGuiViewport}, ImGuiDockNodeFlags, Ptr{ImGuiWindowClass}), viewport, flags, window_class)
end
```
How can I get a ImGuiWindowClass object?

**Comment by JamesWrigley** [comment]
Closing this because as of #141 `DockSpaceOverViewport()` is automatically wrapped with the correct default arguments: https://github.com/Gnimuc/CImGui.jl/blob/206783ecdd32760d6b4c915b95dc8ff893f13737/src/wrapper.jl#L2811-L2816
