### ISSUE TITLE
The getproperty and setproperty! method of ImNodesStyle was not provided

### ISSUE THREAD

**Issue by Gnimuc** [Gnimuc/CImGui.jl#82]
### Discussed in https://github.com/Gnimuc/CImGui.jl/discussions/81

<div type='discussions-op-text'>

<sup>Originally posted by **Faresx** March 21, 2023</sup>
The getproperty and setproperty! method of ImNodesStyle was not provided.
```julia
style = imnodes_GetStyle()
unsafe_load(Ptr{Cfloat}(style+0))
```
will crash.</div>

**Comment by JamesWrigley** [comment]
Ah, I didn't see this before. Fixed by #144.
