### ISSUE TITLE
Regenerate new wrapper libraries for fresh ImGui and ImPlot versions?

### ISSUE THREAD

**Issue by sairus7** [Gnimuc/CImGui.jl#84]
Can we?

**Comment by JamesWrigley** [comment]
I'm gonna close this because we have 1.89 support now: https://github.com/Gnimuc/CImGui.jl/releases/tag/v1.89.0

Though I see that 1.90 was just released :eyes: https://github.com/ocornut/imgui/releases/tag/v1.90
