### ISSUE TITLE
SDL Backend Support? 

### ISSUE THREAD

**Issue by Kyjor** [Gnimuc/CImGui.jl#86]
It's mentioned in the readme that SDL support could be added. Do we think that will happen any time soon if at all? Thanks.

**Comment by Kyjor** [comment]
Wanted to bump this. This would be super helpful for me, as I have to use two separate windows, instead of everything in one. I would be willing to implement it myself, if I could be pointed in the right direction.

**Comment by Kyjor** [comment]
Yeah I completely understand. This will be on my long-term backlog. I think I have a lot to learn so this will be a good task to take on after I learn some more about creating these bindings and such. Thanks!

**Comment by Kyjor** [comment]
Turns out long-term meant a couple of days 😄  I've gotten the sdl opengl backend working  (I'm sure there are a lot of issues with it) and rendering UI elements with inputs. I'm really interested in getting the sdl sdlrenderer backend working, and am hacking away at it. Once I get it working, I'll extract it out to its own repo. But for anyone interested, I'm working on it here: https://github.com/Kyjor/JulGame.jl/tree/feature/sdl-imgui-backend

**Comment by JamesWrigley** [comment]
Very nice work :)

**Comment by Kyjor** [comment]
https://github.com/Kyjor/ImGuiSDLBackend.jl 

Both OpenGL and SDL Backends opening and running. There's still bugs to fix and lose ends to tie up, but it's working.
