### ISSUE TITLE
The interface is too small on high dpi screens.

### ISSUE THREAD

**Issue by Losses** [Gnimuc/CImGui.jl#9]
Is it possible to automatically handle high dpi screen problem?

![image](https://user-images.githubusercontent.com/1384036/64073348-12f73c00-cccf-11e9-9f82-570c1bf31dbe.png)

**Comment by Gnimuc** [comment]
You mean the size of the default font is too small? I guess `Roboto-Medium` would be a better choice for high dpi screens.
```
fonts_dir = joinpath(@__DIR__, "..", "fonts")
fonts = CImGui.GetIO().Fonts
CImGui.AddFontFromFileTTF(fonts, joinpath(fonts_dir, "Roboto-Medium.ttf"), 16)
```
