### ISSUE TITLE
Expand tests

### ISSUE THREAD

**Issue by IanButterworth** [Gnimuc/CImGui.jl#98]
#94 reuses the demo code for a test suite but does not expand any sections or interact with elements.

Also there are no visual regression tests. I looked into ways to grab images of the CImGui window but came up short of using ImageMagick to take a screenshot. (unfortunately that functionality isn't exposed by ImageMagick.jl)

**Comment by JamesWrigley** [comment]
What we really want is to use the imgui_test_engine: https://github.com/ocornut/imgui_test_engine
Which don't have any bindings yet, but doing so is on my todo list :crossed_fingers:
